export const FORUM_CLUSTERS_REQUEST = "FORUM_CLUSTERS_REQUEST";
export const FORUM_CLUSTERS_SUCCESS = "FORUM_CLUSTERS_SUCCESS";
export const FORUM_CLUSTERS_FAIL = "FORUM_CLUSTERS_FAIL";

export const FORUM_SUBJECTS_REQUEST = "FORUM_SUBJECTS_REQUEST";
export const FORUM_SUBJECTS_SUCCESS = "FORUM_SUBJECTS_SUCCESS";
export const FORUM_SUBJECTS_FAIL = "FORUM_SUBJECTS_FAIL";

export const FORUM_MESSAGES_REQUEST = "FORUM_MESSAGES_REQUEST";
export const FORUM_MESSAGES_SUCCESS = "FORUM_MESSAGES_SUCCESS";
export const FORUM_MESSAGES_FAIL = "FORUM_MESSAGES_FAIL";

export const FORUM_MESSAGE_ADD_REQUEST = "FORUM_MESSAGE_ADD_REQUEST";
export const FORUM_MESSAGE_ADD_SUCCESS = "FORUM_MESSAGE_ADD_SUCCESS";
export const FORUM_MESSAGE_ADD_FAIL = "FORUM_MESSAGE_ADD_FAIL";
export const FORUM_MESSAGE_ADD_RESET = "FORUM_MESSAGE_ADD_RESET";

export const FORUM_MESSAGE_EDIT_REQUEST = "FORUM_MESSAGE_EDIT_REQUEST";
export const FORUM_MESSAGE_EDIT_SUCCESS = "FORUM_MESSAGE_EDIT_SUCCESS";
export const FORUM_MESSAGE_EDIT_FAIL = "FORUM_MESSAGE_EDIT_FAIL";
export const FORUM_MESSAGE_EDIT_RESET = "FORUM_MESSAGE_EDIT_RESET";

export const FORUM_SUBJECT_ADD_REQUEST = "FORUM_SUBJECT_ADD_REQUEST";
export const FORUM_SUBJECT_ADD_SUCCESS = "FORUM_SUBJECT_ADD_SUCCESS";
export const FORUM_SUBJECT_ADD_FAIL = "FORUM_SUBJECT_ADD_FAIL";
export const FORUM_SUBJECT_ADD_RESET = "FORUM_SUBJECT_ADD_RESET";
