export const INFO_CENTER_ARTICLES_LIST_REQUEST =
  "INFO_CENTER_ARTICLES_LIST_REQUEST";
export const INFO_CENTER_ARTICLES_LIST_SUCCESS =
  "INFO_CENTER_ARTICLES_LIST_SUCCESS";
export const INFO_CENTER_ARTICLES_LIST_FAIL = "INFO_CENTER_ARTICLES_LIST_FAIL";

export const INFO_CENTER_ARTICLE_GET_REQUEST =
  "INFO_CENTER_ARTICLE_GET_REQUEST";
export const INFO_CENTER_ARTICLE_GET_SUCCESS =
  "INFO_CENTER_ARTICLE_GET_SUCCESS";
export const INFO_CENTER_ARTICLE_GET_FAIL = "INFO_CENTER_ARTICLE_GET_FAIL";
