export const REPORT_ADD_REQUEST = "REPORTS_ADD_REQUEST";
export const REPORT_ADD_SUCCESS = "REPORTS_ADD_SUCCESS";
export const REPORT_ADD_FAIL = "REPORTS_ADD_FAIL";
export const REPORT_ADD_RESET = "REPORTS_ADD_RESET";

export const REPORTS_REQUEST = "REPORTS_REQUEST";
export const REPORTS_SUCCESS = "REPORTS_SUCCESS";
export const REPORTS_FAIL = "REPORTS_FAIL";
