export const PORTFOLIO_FETCH_REQUEST = "PORTFOLIO_FETCH_REQUEST";
export const PORTFOLIO_FETCH_SUCCESS = "PORTFOLIO_FETCH_SUCCESS";
export const PORTFOLIO_FETCH_FAIL = "PORTFOLIO_FETCH_FAIL";

export const PORTFOLIO_LATEST_LIST_REQUEST = "PORTFOLIO_LATEST_LIST_REQUEST";
export const PORTFOLIO_LATEST_LIST_SUCCESS = "PORTFOLIO_LATEST_LIST_SUCCESS";
export const PORTFOLIO_LATEST_LIST_FAIL = "PORTFOLIO_LATEST_LIST_FAIL";
